### ISSUE TITLE
UE5.2.0 Windows Packaging Error 

### ISSUE THREAD

**Issue by ShareQiu1994** [CesiumGS/cesium-unreal#1127]
How to solve the following error when executing the packaging command？

```
UATHelper: 打包 (Windows): LogShaderCompilers: Display: ================================================
UATHelper: 打包 (Windows): LogShaderCompilers: Display: === FShaderJobCache stats ===
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Total job queries 492, among them cache hits 0 (0.00%)
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Tracking 476 distinct input hashes that result in 346 distinct outputs (72.69%)
UATHelper: 打包 (Windows): LogShaderCompilers: Display: RAM used: 5.91 MiB of 1.60 GiB budget. Usage: 0.36%
UATHelper: 打包 (Windows): LogShaderCompilers: Display: === Shader Compilation stats ===
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Shaders Compiled: 492
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Jobs assigned 492, completed 492 (100.00%)
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Average time worker was idle: 0.34 s
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Time job spent in pending queue: average 8.78 s, longest 49.99 s
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Job execution time: average 13.41 s, max 54.32 s
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Job life time (pending + execution): average 22.19 s, max 80.28
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Time at least one job was in flight (either pending or executed): 88.70 s
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Jobs were issued in 92 batches (only local compilation was used), average 5.35 jobs/batch
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Average processing rate: 5.55 jobs/sec
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Total thread time: 987.262 s
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Total thread preprocess time: 15.059 s
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Percentage time preprocessing: 1.53%
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Effective parallelization: 11.13 (times faster than compiling all shaders on one thread). Compare with number of workers: 12
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Top 5 most expensive shader types by average time:
UATHelper: 打包 (Windows): LogShaderCompilers: Display:       TBasePassPSFCachedVolumeIndirectLightingPolicySkylight (compiled   24 times, average 3.96 sec, max 15.12 sec, min 0.82 sec)
UATHelper: 打包 (Windows): LogShaderCompilers: Display:          TBasePassPSTDistanceFieldShadowsAndLightMapPolicyHQ (compiled    8 times, average 3.91 sec, max 15.56 sec, min 0.84 sec)
UATHelper: 打包 (Windows): LogShaderCompilers: Display:                         TBasePassPSTLightMapPolicyLQSkylight (compiled    8 times, average 3.87 sec, max 14.18 sec, min 0.86 sec)
UATHelper: 打包 (Windows): LogShaderCompilers: Display:                         TBasePassPSTLightMapPolicyHQSkylight (compiled    8 times, average 3.73 sec, max 15.40 sec, min 0.75 sec)
UATHelper: 打包 (Windows): LogShaderCompilers: Display:  TBasePassPSTDistanceFieldShadowsAndLightMapPolicyHQSkylight (compiled    8 times, average 3.70 sec, max 16.32 sec, min 0.82 sec)
UATHelper: 打包 (Windows): LogShaderCompilers: Display: Top 5 shader types by total compile time:
UATHelper: 打包 (Windows): LogShaderCompilers: Display:       TBasePassPSFCachedVolumeIndirectLightingPolicySkylight - 9.63% of total time (compiled   24 times, average 3.96 sec, max 15.12 sec, min 0.82 sec)
UATHelper: 打包 (Windows): LogShaderCompilers: Display:               TBasePassPSFCachedVolumeIndirectLightingPolicy - 8.64% of total time (compiled   24 times, average 3.55 sec, max 15.29 sec, min 0.84 sec)
UATHelper: 打包 (Windows): LogShaderCompilers: Display: TBasePassPSFPrecomputedVolumetricLightmapLightingPolicySkylight - 6.80% of total time (compiled   20 times, average 3.36 sec, max 15.20 sec, min 0.90 sec)
UATHelper: 打包 (Windows): LogShaderCompilers: Display:                         TBasePassPSFNoLightMapPolicySkylight - 6.70% of total time (compiled   20 times, average 3.31 sec, max 14.85 sec, min 0.76 sec)
UATHelper: 打包 (Windows): LogShaderCompilers: Display:        TBasePassPSFCachedPointIndirectLightingPolicySkylight - 6.58% of total time (compiled   20 times, average 3.25 sec, max 15.63 sec, min 0.89 sec)
UATHelper: 打包 (Windows): LogShaderCompilers: Display: ================================================
UATHelper: 打包 (Windows): Took 104.6246646s to run UnrealEditor-Cmd.exe, ExitCode=1
UATHelper: 打包 (Windows): ERROR: Cook failed.
UATHelper: 打包 (Windows):        (see C:\Users\liubf\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.2\Log.txt for full exception trace)
UATHelper: 打包 (Windows): AutomationTool executed for 0h 1m 45s
UATHelper: 打包 (Windows): AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)
UATHelper: 打包 (Windows): BUILD FAILED
```

Log.txt

```
ERROR: Cook failed.
       (see C:\Users\liubf\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.2\Log.txt for full exception trace)

CommandletException: Editor terminated with exit code 1 while running Cook for C:\Users\liubf\Documents\Unreal Projects\MyCeisumTest\MyCeisumTest.uproject; see log C:\Users\liubf\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.2\Cook-2023.06.10-14.33.30.txt
   at AutomationTool.CommandUtils.FinishRunCommandlet(FileReference ProjectName, String Commandlet, DateTime StartTime, IProcessResult RunResult, String LocalLogFile, String& DestLogFile, Int32 ErrorLevel) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\CommandletUtils.cs:line 441
   at AutomationTool.CommandUtils.CookCommandlet(FileReference ProjectName, String UnrealExe, String[] Maps, String[] Dirs, String InternationalizationPreset, String[] CulturesToCook, String TargetPlatform, String Parameters) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\CommandletUtils.cs:line 90
   at AutomationScripts.Project.Cook(ProjectParams Params) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Scripts\CookCommand.Automation.cs:line 291Wrapped by AutomationException: Cook failed.
   at AutomationScripts.Project.Cook(ProjectParams Params) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Scripts\CookCommand.Automation.cs:line 301
   at BuildCookRun.DoBuildCookRun(ProjectParams Params) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 221
   at BuildCookRun.ExecuteBuild() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 42
   at AutomationTool.BuildCommand.Execute() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 344
   at AutomationTool.BuildCommand.ExecuteAsync() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 353
   at AutomationTool.Automation.ExecuteAsync(List`1 CommandsToExecute, Dictionary`2 Commands) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 257
   at AutomationTool.Automation.ProcessAsync(ParsedCommandLine AutomationToolCommandLine, StartupTraceListener StartupListener, HashSet`1 ScriptModuleAssemblies) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 156
==============================================================================
AutomationTool executed for 0h 1m 45s
AutomationTool exiting with ExitCode=25 (Error_UnknownCookFailure)
```

**Comment by ShareQiu1994** [comment]
[Cook-2023.06.10-14.39.06.txt](https://github.com/CesiumGS/cesium-unreal/files/11711771/Cook-2023.06.10-14.39.06.txt)

**Comment by AntonMikhet** [comment]
and Linux same

**Comment by kring** [comment]
I don't think you've included enough of the log to see what's going on, and the link to the full log is broken. Can either or both of you please post your complete package logs?

**Comment by ShareQiu1994** [comment]
[Cook-2023.06.13-11.27.20.txt](https://github.com/CesiumGS/cesium-unreal/files/11730410/Cook-2023.06.13-11.27.20.txt)
[Log.txt](https://github.com/CesiumGS/cesium-unreal/files/11730411/Log.txt)

**Comment by ShareQiu1994** [comment]
Sorry, this is my packaging log，  I have no problem packaging using the official example CesiumForUnrealSamples v1.27.1.  But I created a simple example myself according to the official document tutorial, but I reported an error when packaging it

@kring

**Comment by kring** [comment]
I think the relevant error is this one:

> 碰撞描述文件设置不包括水体碰撞描述文件的条目，水碰撞必须使用该描述文件才能正常工作。 将条目添加到DefaultEngine.ini？

Translated to English:

> The Collision Profiles settings do not include an entry for the water body collision profile, which is required for water collisions to work properly. Add entry to DefaultEngine.ini?

Which sounds the same as described and solved here:
https://community.cesium.com/t/i-want-to-hide-part-of-a-set-of-photorealistic-3d-tiles-in-google-and-place-other-levels-that-i-have-created-myself-there/24290/6

I'm closing this, but please follow up on the community forum if you still have trouble.

**Comment by ShareQiu1994** [comment]
The problem has been resolved

Thanks
